### ISSUE TITLE
NPM Forge doesn't match API

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/integration-bdio#7]
So I'm creating an external ID using the NPM forge located here which uses an "@" 
https://github.com/blackducksoftware/integration-bdio/blob/master/src/main/java/com/blackducksoftware/integration/hub/bdio/simple/model/Forge.java#L44

However if I request the components back from BlackduckHub then they come in this form with a "/": (Some json excluded to keep it brief:
```
{
            "componentName": "node-assert-plus",
            "componentVersionName": "1.0.0",
            ...
            "origins": [
                {
                    "name": "1.0.0",
                    "externalNamespace": "npmjs",
                    "externalId": "assert-plus/1.0.0",
                    ...
```

On other forges that I've tried these have matched. Is there a reason these don't seem to match?

**Comment by ekerwin** [comment]
I have been told that the '@' symbol is required for Hub input, but it is not preserved after the fact. Npm is not the only forge for which this is true, but hopefully coming in 2018, there will be better consistency. I'll double-check tomorrow against the latest release of the Hub (4.4.0) to see if they still are requiring the '@' in bdio external identifiers for matching on upload. If they do, I'll update and close this issue.

**Comment by ekerwin** [comment]
@imbeyondboredom I do not believe the '@' symbol is expressly required anymore, but I am still being told to keep it that way. I am opening a ticket against the Hub to try and make things more consistent. For now, this is the way it will stay even though I wish it were otherwise. Thanks for your input!
